#!/bin/bash

# $1 will be /execution/keystore
touch $(dirname "$1")/password.txt

# look for keystore files in /execution/keystore
# if there are none, create a new keystore file
if [ -z "$(find $(dirname "$1") -type f -name "UTC*")" ]; then
  geth --datadir=$(dirname "$1") account new --lightkdf --password  $(dirname "$1")/password.txt --keystore $1
fi
