#!/bin/bash

set -e -u -o pipefail

url=${1:-"http://localhost:8545"}

# Make the RPC request
data='{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
set -x
curl -sS -X POST -H "Content-Type: application/json" -d "$data" "$url"
